# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "9300:9300"
    - "5000:5000"
